#!/bin/bash
set -a
source .env
set +a
# Run the Spring Boot application with debugging enabled
mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
