# yaml
name: Deploy Spring Boot to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare artifact
        run: |
          JAR_FILE=$(ls backend/target/*.jar | grep -v 'original' | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "No JAR found in backend/target/"
            exit 1
          fi
          zip -j app.zip "$JAR_FILE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 and deploy to Elastic Beanstalk
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          EB_APP: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENV: ${{ secrets.EB_ENVIRONMENT_NAME }}
        run: |
          VERSION_LABEL=${{ github.sha }}-$(date +%Y%m%d%H%M%S)
          aws s3 cp app.zip "s3://${S3_BUCKET}/${VERSION_LABEL}.zip"
          aws elasticbeanstalk create-application-version \
            --application-name "${EB_APP}" \
            --version-label "${VERSION_LABEL}" \
            --source-bundle S3Bucket="${S3_BUCKET}",S3Key="${VERSION_LABEL}.zip"
          aws elasticbeanstalk update-environment \
            --environment-name "${EB_ENV}" \
            --version-label "${VERSION_LABEL}"
